#!/usr/bin/env bash

CUR_STABLE="$(ls -lt stable/features/org.openbel.workbench*.jar \
            | egrep -o "[0-9]+.jar" \
            | cut -d '.' -f1 \
            | head -n 1)"
if [ ! -z "${CUR_STABLE}" ]; then
    echo -en "Relocating current stable to ${CUR_STABLE}... "
    if [ ! -d "${CUR_STABLE}" ]; then
        cp -a "stable" "${CUR_STABLE}"
    fi
    echo -en "okay\n"
fi

echo -en "Recreating stable and unstable... "
rm -fr stable unstable
mkdir -p stable unstable
echo -en "okay\n"

### UNSTABLE ###
echo
echo -en "Updating unstable.\n"
# GRAB IT FROM BAMBOO
BUILD_KEY="browse/BELEDITOR-BUILDUNSTABLE"
ARTIFACT="unstable-repository.zip"
LATEST="${BUILD_KEY}/latestSuccessful/artifact/JOB1/repository-zip/${ARTIFACT}"
wget --quiet http://ci.selventa.com/${LATEST} || exit 1
echo "Got $(/bin/ls -sh ${ARTIFACT} | awk '{ print $1 }') from Bamboo."

# EXTRACT IT
echo -en "Extracting... "
cd unstable || exit 1
unzip -oqq ../${ARTIFACT}
cd - >/dev/null || exit 1
echo "okay"

# WACK THE ARTIFACT
echo -en "Removing artifact... "
rm ${ARTIFACT} || exit 1
echo "okay"


### STABLE ###
echo
echo -en "Updating stable.\n"
# GRAB IT FROM BAMBOO
BUILD_KEY="browse/BELEDITOR-BUILDSTABLE"
ARTIFACT="stable-repository.zip"
LATEST="${BUILD_KEY}/latestSuccessful/artifact/JOB1/repository-zip/${ARTIFACT}"
wget --quiet http://ci.selventa.com/${LATEST} || exit 1
echo "Got $(/bin/ls -sh ${ARTIFACT} | awk '{ print $1 }') from Bamboo."

# EXTRACT IT
echo -en "Extracting... "
cd stable || exit 1
unzip -oqq ../${ARTIFACT}
cd - >/dev/null || exit 1
echo "okay"

# WACK THE ARTIFACT
echo -en "Removing artifact... "
rm ${ARTIFACT} || exit 1
echo "okay"

